### PR TITLE
Fix small typo, foreEach => forEach

### PR DESCRIPTION
**Pull request by PatrickKalkman**
Hi, thanks for the program. I am using it for a small video encoder in node. I stumbled into this small bug and created a PR for it.

Kind regards,
Patrick

### CODE REVIEW

**Comment by franzyke** [comment]
#3 

Looks like its not being merged :D

**Comment by PatrickKalkman** [comment]
> #3
> 
> Looks like its not being merged :D

I guess not. It is a pity though, it is a nice project.

**Comment by markusdaehn** [comment]
@PatrickKalkman @franzyke Let me know if you guys are using this library or would like to be added to it to fix any issues. I have been away from working on any open source projects lately but have started to get back into it.

**Comment by PatrickKalkman** [comment]
> @PatrickKalkman @franzyke Let me know if you guys are using this library or would like to be added to it to fix any issues. I have been away from working on any open source projects lately but have started to get back into it.

Hi @markusdaehn, yes I am currently using the library for a video encoder. Let me know, how I can help.

**Comment by franzyke** [comment]
Yeah me too. And will probably use it again in an upcoming project

**Pull request merged**
